services:
    rabbitmq:
      image: rabbitmq:3-manegement
      container_name: rabbitmq
      ports:
       - '5672:5672' #AMQP Protocol
       -  '15672:15672' #UI
      enviroments:
        RABBIT_MQ_DEFAULT_USER: guest
        RABBIT_MQ_DEFAULT_PASS: guest
        